### PR TITLE
Updated Theme with support for plugins and other cool stuff

### PR DESCRIPTION
**Pull request by GhostLordGabi**
Hello it's me, MaBoiGabi:
---

First of all:
Fixed all of the selectors, they got completely different names when Discord decided to ~~destroy~~ 'enhance' their CSS. But I tried to change a few things that I thought might work quite well with it. Feel free to change it again.

Features:
---

**Styled user Popouts*
userpopout

**Styled user profile Modal*
profilemodal

**Styled buttons*
profilemodalsendfriendrequest

**Owner-Tag Support & Bot-Tag Support*
- Owner Tag:
profilemodalownertag
- Bot Tag:
userpopoutbot
profilemodalbot

**Profile picture-Addon Support (Just shows up, when plugin is installed)*
- Plugin installed:
userpopoutprofilepic
- Plugin *not installed*:
userpopoutprofilepicnotinstalled

I wrote that in the PTB-Version of Discord, using BetterDiscord. I do hope that everything works in BeautifulDiscord as well, but it should work like intended.
But there are some bugs:

Known Bugs:
---

**Streaming*
streamingbug1
streamingbug2

Thanks for the great idea, hope you accept my pull request. If you want me to change something just write me. Thanks for reading!

### CODE REVIEW

**Comment by TripingPC** [comment]
Looks absolutely amazing.

**Comment by GhostLordGabi** [comment]
Thanks for the merge :)

**Comment by TripingPC** [comment]
Actually, most users have a deobfuscation script. And the numbers and letters are only yours.  Remove them or I'll do it when I wake up.

**Comment by GhostLordGabi** [comment]
I am not entirely sure what you mean. What letters and numbers? And what do you mean with deobfuscation script?

**Comment by TripingPC** [comment]
The fact you're using PTB instead of Canary shows you don't know the whole situation.  I'll fix it myself later...

**Pull request merged**
